
TYPE
	PuckPosition_Enum : 
		(
		PUCKPOS_IN_MAG := 0,
		PUCKPOS_IN_TRANSIT := 1,
		PUCKPOS_IN_TRAY := 2,
		PUCKPOS_GRIPPED_AT_TRAY := 3,
		PUCKPOS_IN_SWIVEL := 4,
		PUCKPOS_GRIPPED_AT_CONV := 5,
		PUCKPOS_CONV_START := 6,
		PUCKPOS_CONV_MID := 7,
		PUCKPOS_CONV_END := 8
		);
	MainAutoStep_typ : 	STRUCT 
		DIST_INIT : BOOL;
		DIST_EXTEND_EJECTOR : BOOL;
		DIST_RETRACT_EJECTOR : BOOL;
		DIST_SWIVEL_TO_PICKUP : BOOL;
		DIST_SWIVEL_PICKUP : BOOL;
		DIST_SWIVEL_TO_CONV : BOOL;
		DIST_SWIVEL_DROP : BOOL;
		DIST_SWIVEL_TO_MAG : BOOL;
		DIST_CONV_START : BOOL;
		DIST_CONV_MOVING : BOOL;
		DIST_CONV_END : BOOL;
		DIST_WAIT : BOOL;
		DIST_SWIVEL_TO_HOME : BOOL;
	END_STRUCT;
	MainMode_typ : 	STRUCT 
		Auto : BOOL;
		Manual : BOOL;
	END_STRUCT;
END_TYPE
